line.bot:
  channel-token: 'PhH3sS7NjFVPSmYJi1EfUBQvjKI69K+VgqIpAcgX8Gs3ezbp/2Q9fXu+F0hABVX0LNb4IJep0LvNSfFqKBkAkVXalwYdsCMO1uj4CdmYNEorEboY4igZ41sr79HHlDc7rZvcZfBPYp0oeKdawJe2YAdB04t89/1O/w1cDnyilFU='
  channel-secret: '1f0050f3c9e3c96590dca05727eb18d8'
  handler.path: /callback